import Head from 'next/head'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (  
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-3xl font-bold'>Next Ecommerce</h1>
      </main>
    </>
  )
}
